# Generated by Django 5.2.6 on 2025-09-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacie',
            name='est_ouvert',
        ),
        migrations.RemoveField(
            model_name='pharmacie',
            name='heures_ouverture',
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
