# Generated by Django 5.2.3 on 2025-09-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pharmacie_est_ouvert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='min_stock',
            field=models.IntegerField(default=0),
        ),
    ]
