# Generated by Django 5.0.6 on 2025-11-30 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medication_min_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['nom'], 'verbose_name': 'Médicament', 'verbose_name_plural': 'Médicaments'},
        ),
        migrations.AlterModelOptions(
            name='pharmacie',
            options={'ordering': ['nom'], 'verbose_name': 'Pharmacie', 'verbose_name_plural': 'Pharmacies'},
        ),
        migrations.AlterModelOptions(
            name='pharmacymedication',
            options={'verbose_name': 'Stock Pharmacie-Médicament', 'verbose_name_plural': 'Stocks Pharmacie-Médicament'},
        ),
        migrations.AlterField(
            model_name='medication',
            name='categorie',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='note',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='pharmacymedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_stocks', to='api.medication'),
        ),
        migrations.AlterField(
            model_name='pharmacymedication',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='api.pharmacie'),
        ),
        migrations.AlterField(
            model_name='pharmacymedication',
            name='stock_disponible',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['nom'], name='medication_name_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['categorie'], name='medication_category_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacie',
            index=models.Index(fields=['latitude', 'longitude'], name='location_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacie',
            index=models.Index(fields=['note'], name='rating_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacymedication',
            index=models.Index(fields=['pharmacy', 'medication'], name='pharmacy_med_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacymedication',
            index=models.Index(fields=['stock_disponible'], name='stock_idx'),
        ),
    ]
