# Generated by Django 5.0.6 on 2025-12-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_medication_options_alter_pharmacie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dci',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Dénomination Commune Internationale'),
        ),
    ]
