# Generated by Django 5.2.3 on 2025-09-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prescription_file',
        ),
    ]
